spring:
  application:
    name: apollo-portal
  profiles:
    active: ${apollo_profile}
<<<<<<< HEAD
  ldap:
    username:
    password:
    base:
    searchFilter:
    urls:
ldap:
  mapping:
    objectClass:
    loginId:
    userDisplayName:
    email:
    filterBase:
=======
  jpa:
    properties:
      hibernate:
        query:
          plan_cache_max_size: 192 # limit query plan cache max size

>>>>>>> apollo-master/master
server:
  port: 8070
  compression:
<<<<<<< HEAD
      enabled: true
=======
    enabled: true
  tomcat:
    use-relative-redirects: true
>>>>>>> apollo-master/master

logging:
  file: /opt/logs/100003173/apollo-portal.log

management:
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP 


