spring:
  application:
    name: apollo-portal
  profiles:
    active: ${apollo_profile}
  ldap:
    username:
    password:
    base:
    searchFilter:
    urls:
ldap:
  mapping:
    objectClass:
    loginId:
    userDisplayName:
    email:
    filterBase:
server:
  port: 8080
  compression:
      enabled: true

logging:
  file: /opt/logs/100003173/apollo-portal.log

management:
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP 


